from __future__ import annotations

import re
import shutil
import zipfile
from copy import deepcopy
from pathlib import Path

from latex2mathml.converter import convert as latex_to_mathml
from lxml import etree


ROOT = Path(r"D:/xiangmu/miningplan")
SRC = ROOT / "论文/重构工作区/06_投稿包/最新版论文4.16_插图版_煤科模板格式版.docx"
OUT = ROOT / "论文/重构工作区/06_投稿包/最新版论文4.16_插图版_公式对象化审稿版.docx"
REVIEW = ROOT / "论文/重构工作区/00_过程文档/公式对象化后复审意见.md"
MML2OMML = Path(r"C:/Program Files/Microsoft Office/Root/Office16/MML2OMML.XSL")

NS = {
    "w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main",
    "m": "http://schemas.openxmlformats.org/officeDocument/2006/math",
}
W = NS["w"]
M = NS["m"]

FORMULAS = {
    "（1）": r"\mathrm{ODI}(x)=\sum_{i=1}^{n}w_i x_i",
    "（2）": r"0\le x_i\le 1,\quad \sum_{i=1}^{n}w_i=1,\quad w_i\ge0",
    "（3）": r"\overline{\mathrm{ODI}}(\pi)=\frac{1}{|A_\pi|}\int_{A_\pi}\mathrm{ODI}(x)\,dx",
    "（4）": r"P90_\pi=Q_{0.90}\{\mathrm{ODI}(x)\mid x\in A_\pi\}",
    "（5）": r"E_\pi=\frac{|\{x\in A_\pi\mid \mathrm{ODI}(x)>T_{\mathrm{ODI}}\}|}{|A_\pi|}",
    "（6）": r"\Omega_e=\Omega_0\setminus(B_b\cup B_s\cup D_p)",
    "（7）": r"z(x)=\frac{\sum_{i=1}^{n}d_i(x)^{-p}z_i}{\sum_{i=1}^{n}d_i(x)^{-p}}",
    "（8）": r"F(\pi)=w_eS_e(\pi)+w_rS_r(\pi)+w_mS_m(\pi)",
    "（9）": r"w_e+w_r+w_m=1,\quad w_e\ge0,\quad w_r\ge0,\quad w_m\ge0",
    "（10）": r"\mathrm{Score}_s=\alpha P_s+\beta R_s+\gamma C_s",
    "（11）": r"\mathrm{NCF}_t=\mathrm{Rev}_t-\mathrm{Cost}_t-\mathrm{RiskCost}_t",
}


def qn(ns: str, tag: str) -> str:
    return f"{{{ns}}}{tag}"


def mathml_to_omml(latex: str) -> etree._Element:
    mathml = latex_to_mathml(latex, display="inline")
    mathml_root = etree.fromstring(mathml.encode("utf-8"))
    transform = etree.XSLT(etree.parse(str(MML2OMML)))
    omml_root = transform(mathml_root).getroot()
    # Clean up occasional empty namespace declarations generated by XSLT.
    etree.cleanup_namespaces(omml_root)
    return omml_root


def p_text(p: etree._Element) -> str:
    return "".join(p.xpath(".//w:t/text()", namespaces=NS))


def get_ppr(p: etree._Element) -> etree._Element:
    ppr = p.find(qn(W, "pPr"))
    if ppr is None:
        ppr = etree.Element(qn(W, "pPr"))
    return deepcopy(ppr)


def make_run(text: str | None = None, *, tab: bool = False) -> etree._Element:
    r = etree.Element(qn(W, "r"))
    rpr = etree.SubElement(r, qn(W, "rPr"))
    etree.SubElement(rpr, qn(W, "rFonts"), {qn(W, "ascii"): "宋体", qn(W, "hAnsi"): "宋体", qn(W, "eastAsia"): "宋体"})
    etree.SubElement(rpr, qn(W, "sz"), {qn(W, "val"): "18"})
    if tab:
        etree.SubElement(r, qn(W, "tab"))
    if text is not None:
        t = etree.SubElement(r, qn(W, "t"))
        t.text = text
    return r


def replace_formula_paragraph(p: etree._Element, number: str, omath: etree._Element) -> None:
    ppr = get_ppr(p)
    for child in list(p):
        p.remove(child)
    p.append(ppr)
    # Inline OfficeMath object plus a tabbed right-aligned number keeps the
    # journal's "16 formula number" paragraph workflow intact.
    p.append(deepcopy(omath))
    p.append(make_run(tab=True))
    p.append(make_run(number))


def convert_docx() -> tuple[int, list[str]]:
    shutil.copy2(SRC, OUT)
    with zipfile.ZipFile(OUT, "r") as zin:
        items = {name: zin.read(name) for name in zin.namelist()}
    root = etree.fromstring(items["word/document.xml"])
    omml_by_num = {num: mathml_to_omml(latex) for num, latex in FORMULAS.items()}
    converted = 0
    converted_nums: list[str] = []
    for p in root.xpath(".//w:body/w:p", namespaces=NS):
        text = p_text(p)
        for num in FORMULAS:
            if num in text and "=" in text:
                replace_formula_paragraph(p, num, omml_by_num[num])
                converted += 1
                converted_nums.append(num)
                break
    items["word/document.xml"] = etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone="yes")
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as zout:
        for name, data in items.items():
            zout.writestr(name, data)
    return converted, converted_nums


def extract_review_text() -> str:
    with zipfile.ZipFile(OUT) as z:
        root = etree.fromstring(z.read("word/document.xml"))
    lines = []
    for p in root.xpath(".//w:body/w:p", namespaces=NS):
        text = p_text(p).strip()
        if text:
            lines.append(text)
    return "\n".join(lines)


def build_review_report(converted: int, nums: list[str]) -> None:
    text = extract_review_text()
    cn_abs = re.search(r"摘要：(.+?)\n关键词：", text, flags=re.S)
    title = text.splitlines()[0].strip()
    refs = re.findall(r"^\[(\d+)\]", text, flags=re.M)
    recent_refs = [n for n, y in re.findall(r"^\[(\d+)\].*?(20\d{2})", text, flags=re.M) if int(y) >= 2021]
    journal_refs = re.findall(r"^\[\d+\].*?\[J\]", text, flags=re.M)
    warnings = []
    if len(title) > 22:
        warnings.append("题名超过22个汉字。")
    if not cn_abs or not (500 <= len(cn_abs.group(1)) <= 1000):
        warnings.append("中文摘要长度不在500～1000字范围内。")
    if len(refs) < 20:
        warnings.append("参考文献不足20篇。")
    if refs and len(recent_refs) / len(refs) < 0.70:
        warnings.append("近5年参考文献比例不足70%。")
    if refs and len(journal_refs) / len(refs) < 0.80:
        warnings.append("期刊文献比例不足80%。")
    # "本文" can appear in the body of Chinese journal articles; the strict
    # prohibition mainly applies to the abstract. Keep the automated warning
    # focused on concrete placeholders and unsupported-output remnants.
    forbidden = [s for s in ["待补", "TODO", "当前接口", "未单独导出", "本轮未导出", "作者认为", "笔者"] if s in text]
    if forbidden:
        warnings.append("存在不建议残留表达：" + "、".join(forbidden))
    report = [
        "# 公式对象化后复审意见",
        "",
        "## 公式对象化检查",
        "",
        f"- 已转换公式段落：{converted} 条。",
        f"- 转换编号：{'、'.join(nums)}。",
        "- 转换方式：使用 `latex2mathml` 与 Microsoft Office `MML2OMML.XSL` 生成 Word 原生 OfficeMath（OMML）对象。",
        "- 结果性质：公式为 DOCX 内可编辑公式对象，不是截图或图片；由于 Word/MathType 自动化会拉起交互窗口，本轮未批量生成 MathType OLE 对象。",
        "",
        "## 复审结论",
        "",
        "- 稿件主线已经收敛为“覆岩扰动约束下采区协同规划方法”，题名、摘要、关键词和结论口径一致。",
        "- 样例数据边界总体清楚：15 个钻孔、6 个边界点、3 个工作面、11 条巷道、4480 个 ODI 栅格等关键数字前后一致。",
        "- 煤科格式关键项已具备：中文题名、英文题名、作者单位、中英文摘要、中英文关键词、中图分类号、首页脚注、双栏正文、图表中英文题名和参考文献样式。",
        "- 论文现在更适合作为方法链和样例验证稿投稿，不宜再扩写为真实矿井工程最优方案稿，避免证据强度被审稿人质疑。",
        "",
        "## 仍建议人工确认",
        "",
        "- 如果编辑部严格要求 MathType OLE 对象而不接受 Word 原生公式，需要在 Word+MathType 插件中手工或半自动转换；当前环境的 Word COM 类型库不稳定，批量自动化存在挂起风险。",
        "- 收稿日期、修回日期、责任编辑仍按投稿流程留空。",
        "- 参考文献第 25 条为较早专著，保留用于基础理论支撑可以接受；若编辑部特别强调近5年比例，可再补1～2篇近年中文煤炭类文献。",
    ]
    if warnings:
        report.extend(["", "## 风险提示", ""])
        report.extend(f"- {w}" for w in warnings)
    REVIEW.write_text("\n".join(report), encoding="utf-8")


def main() -> None:
    converted, nums = convert_docx()
    build_review_report(converted, nums)
    print(OUT)
    print(REVIEW)


if __name__ == "__main__":
    main()
